DICT_SMILEY = {
    ":-)": "smiley",
    ":)": "smiley",
    ";)": "smiley",
    ";-)": "smiley",
    ":D": "smiley",
    "xD": "smiley",
    ":’)": "smiley",
    ":’D": "smiley",
    ":3": "smiley",
    ":]": "smiley",
    ":^)": "smiley",
    ":-]": "smiley",
    ":-3": "smiley",
    ":->": "smiley",
    ":))": "smiley",
    "8-)": "cool",
    "8)": "cool",
    "8-D": "cool",
    "B)": "cool",
    "BD": "cool",
    ":-}": "smiley",
    ":>": "smiley",
    ":}": "smiley",
    ":o)": "smiley",
    ":c)": "smiley",
    "=)": "smiley",
    "=D": "smiley",
    "=]": "smiley",
    ":-D": "smiley",
    "XD": "smiley",
    ":o": "surprised",
    ":O": "surprised",
    "=o": "surprised",
    "=O": "surprised",
    ":0": "surprised",
    ":(": "sad",
    ":C": "sad",
    ":c": "sad",
    "=(": "sad",
    "=c": "sad",
    "=C": "sad",
    ":-(": "sad",
    ":-c": "sad",
    ":-C": "sad",
    ":-<": "sad",
    ":<": "sad",
    ":[": "sad",
    ":{": "sad",
    ":’(": "crying",
    ";p": "playful",
    ";P": "playful",
    ";-p": "playful",
    ";-P": "playful",
    ":P": "playful",
    ":p": "playful",
    "xP": "playful",
    "XP": "playful",
    "=P": "playful",
    "=p": "playful",
    "xp": "playful",
    "xb": "playful",
    "<3": "love",
    "</3": "sad",
    ":/": "worried",
    ":-/": "worried"
}

WORDS_TO_KEEP = ["don", "don't", "ain", "aren", "aren't", "couldn", "couldn't", "didn", "didn't", "doesn", "doesn't",
                 "hadn", "hadn't", "hasn", "hasn't", "haven", "haven't", "isn", "isn't", "ma", "mightn", "mightn't",
                 "mustn", "mustn't", "needn", "needn't", "shan", "shan't", "no", "nor", "not", "shouldn", "shouldn't",
                 "wasn", "wasn't", "weren", "weren't", "won", "won't", "wouldn", "wouldn't"]
